name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: cotyhamilton
      IMAGE_REPO: hello-deno
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: docker build --file $DOCKERFILE --tag $DOCKERHUB_USERNAME/$IMAGE_REPO:${{ github.run_id }} --tag $DOCKERHUB_USERNAME/$IMAGE_REPO:latest $CONTEXT
      env:
        DOCKERFILE: hello/Dockerfile
        CONTEXT: hello
    - name: Push
      run: docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:${{ github.run_id }}
    - name: Push Latest
      if: github.ref == 'ref/head/main'
      run: docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:latest
