name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: cotyhamilton
      IMAGE_REPO: hello-deno
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: docker build --file $DOCKERFILE --tag $DOCKERHUB_USERNAME/$IMAGE_REPO:${{ github.run_id }} --tag $DOCKERHUB_USERNAME/$IMAGE_REPO:latest $CONTEXT
      env:
        DOCKERFILE: hello/Dockerfile
        CONTEXT: hello
    - name: Push
      run: docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:${{ github.run_id }}
    - name: Push Latest
      if: github.ref == 'refs/heads/main'
      run: docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:latest
  staging:
    needs: build
#     if: github.ref == 'refs/heads/action'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: testing
        run: echo ${{ github.run_id }} ${{ github.event_name }}
