name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deployStaging:
        description: Deploy to Staging
        default: 'false'
      deployProduction:
        description: Deploy to Production
        default: 'false'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: cotyhamilton
      IMAGE_REPO: hello-deno
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build
      run: docker build --file $DOCKERFILE --tag $DOCKERHUB_USERNAME/$IMAGE_REPO:${{ github.run_id }} --tag $DOCKERHUB_USERNAME/$IMAGE_REPO:latest $CONTEXT
      env:
        DOCKERFILE: hello/Dockerfile
        CONTEXT: hello
    - name: Push
      run: docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:${{ github.run_id }}
    - name: Push Latest
      if: github.ref == 'refs/heads/main'
      run: docker push $DOCKERHUB_USERNAME/$IMAGE_REPO:latest
  staging:
    needs: build
    if: github.ref == 'refs/heads/main' || github.event.inputs.deployStaging == 'true'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Deploy
        run: echo Deploying ${{ github.run_id }} to Staging
  production:
    needs: staging
    if: github.ref == 'refs/heads/main' || github.event.inputs.deployProduction == 'true'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy
        run: echo Deploying ${{ github.run_id }} to Production
